### ISSUE TITLE
Login issues Google+

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#977] opened 2017-09-08 06:25 UTC
![image](https://user-images.githubusercontent.com/11202073/30198672-2df8b708-946f-11e7-9a17-625e33a4ba62.png)

This is not the first complaint I get about Google+ of the same nature

**Comment by YLivay** [comment] 2017-09-14 17:46
I responded in the thread, but i'll detail what I think happened here as well.
When you already have a Game Jolt account if you want to add any other social accounts to it you have to first link them through the account settings. What I think happened with Robstruck15 is that his Game Jolt account was already using the email address that belongs to the Google+ account without it being linked to it, so the login is rejected. After all, what happens if someone hacks your Google+ account - does that mean he'll get access to your GJ account as well even tho it wasnt linked to it?

Anyways, if Rob manages to link his account and log in properly please close this issue :)

**Comment by hworld** [comment] 2017-09-26 18:31
closing since this is intended behavior for security reasons

**Closed by hworld** 2017-09-26 18:31 UTC
Labels: awaiting-feedback
