### ISSUE TITLE
Game headers glitch out on my Android device

### ISSUE THREAD

**Issue by Savordez** [gamejolt/issue-tracker#315] opened 2015-06-27 11:58 UTC
Turning the device into landscape and back quickly causes game headers to slightly freak out. I have a Nexus 5.

![headerspls](https://cloud.githubusercontent.com/assets/12786937/8391865/d5cf926a-1cdc-11e5-9c79-1ccdce38138f.png)

**Comment by NikSudan** [comment] 2015-06-27 12:22
Dupe of #314

**Closed by NikSudan** 2015-06-27 12:22 UTC
