### ISSUE TITLE
Cannot Refresh Pages

### ISSUE THREAD

**Issue by Bedlams** [gamejolt/issue-tracker#852] opened 2017-05-13 21:43 UTC
I have to go out of the page and back in in order to see new comments or replies. Please fix

**Comment by hworld** [comment] 2017-06-21 19:48
Is this in the Client?

**Comment by Bedlams** [comment] 2017-06-28 03:22
Yes. A simple refresh button should fix the problem.

**Comment by niksudan** [comment] 2017-06-28 13:29
I don't think new comments appear automatically on the site or client anyway?

**Comment by Bedlams** [comment] 2017-06-29 22:31
They don't, but the site has a refresh button on the web browser.

**Comment by hworld** [comment] 2017-07-31 00:14
closing since dupe of https://github.com/gamejolt/issue-tracker/issues/402

**Closed by hworld** 2017-07-31 00:14 UTC
