### ISSUE TITLE
Add a button to install games from the library screen

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#420] opened 2015-12-23 06:13 UTC
I think it would be very user friendly if there was a way to install games from the game library (e.g. your followed games) screens. A control like the ones for launching/uninstalling games on the installed games screen would be great.

**Comment by hworld** [comment] 2015-12-23 14:22
Mmmm, yeah. I want to get this out in the next update, actually. I'll make playlists much more useful in the Client, as well.

**Comment by YLivay** [comment] 2016-02-05 15:31
Not sure we're going to actually cram it in the new release, but added it anyways

**Comment by hworld** [comment] 2017-12-08 04:02
closing since it's a feature and not a bug. can post in the gj-improve forum if you still desire it. =]

**Closed by hworld** 2017-12-08 04:02 UTC
Labels: client, feature
