### ISSUE TITLE
[Client] Music player doesn't work

### ISSUE THREAD

**Issue by maxlefou** [gamejolt/issue-tracker#715] opened 2016-06-22 10:11 UTC
I searched but haven't found any open issue for that so i'm making one.

The music player found in some games doesn't work at all in the GJ client. When you click on play, no sound comes and the bar doesn't move.

The rest seems to work ok. The player's display works, the download button works (tho, it opens a window in the browser by doing this) It just doesn't play the music itself.

**Comment by hworld** [comment] 2016-06-22 12:20
Hey, thanks for reporting this! It's actually a duplicate of this issue https://github.com/gamejolt/issue-tracker/issues/576

The reason is that since we currently (sadly and embarrassingly) only support MP3 uploads, the client isn't able to play that codec, so it can't play any of the songs. To fix this, we need to allow multiple types of formats to be uploaded and re-encode everything into a format we can support in Client. We haven't had time to do this just yet since it's obviously not an easy change.

**Closed by hworld** 2016-06-22 12:20 UTC
