### ISSUE TITLE
installation has failed

### ISSUE THREAD

**Issue by Umar2002** [gamejolt/issue-tracker#443] opened 2016-01-03 14:57 UTC
2016-01-03 15:43:39> Program: Starting Squirrel Updater: --install .
2016-01-03 15:43:39> Program: Starting install, writing to C:\Users\Umar\AppData\Local\SquirrelTemp
2016-01-03 15:43:40> Program: About to install to: C:\Users\Umar\AppData\Local\GameJoltClient
2016-01-03 15:43:41> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Kan een gedeelte van het pad C:\Users\Umar\AppData\Local\GameJoltClient\packages\RELEASES niet vinden.
   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bij System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bij Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   bij Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
2016-01-03 15:43:41> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Umar\AppData\Local\SquirrelTemp
2016-01-03 15:43:41> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-01-03 15:43:42> ApplyReleasesImpl: Writing files to app directory: C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2
2016-01-03 15:46:12> ApplyReleasesImpl: Moving file C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\lib\net45\GameJoltClient.exe to C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\GameJoltClient.exe
2016-01-03 15:46:12> ApplyReleasesImpl: Moving file C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\lib\net45\icudtl.dat to C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\icudtl.dat
2016-01-03 15:46:12> ApplyReleasesImpl: Moving file C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\lib\net45\libEGL.dll to C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\libEGL.dll
2016-01-03 15:46:12> ApplyReleasesImpl: Moving file C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\lib\net45\nw.pak to C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\nw.pak
2016-01-03 15:46:12> ApplyReleasesImpl: Moving file C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\lib\net45\libGLESv2.dll to C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\libGLESv2.dll
2016-01-03 15:46:12> ApplyReleasesImpl: Moving file C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\lib\net45\package.json to C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\package.json
2016-01-03 15:46:12> ApplyReleasesImpl: Moving file C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\lib\net45\pdf.dll to C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\pdf.dll
2016-01-03 15:46:14> ApplyReleasesImpl: Squirrel Enabled Apps: []
2016-01-03 15:46:14> ApplyReleasesImpl: No apps are marked as Squirrel-aware! Going to run them all
2016-01-03 15:46:14> ApplyReleasesImpl: About to create shortcuts for GameJoltClient.exe, rootAppDir C:\Users\Umar\AppData\Local\GameJoltClient
2016-01-03 15:46:15> ApplyReleasesImpl: Creating shortcut for GameJoltClient.exe => C:\Users\Umar\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Lucent Web Creative\Game Jolt Client.lnk
2016-01-03 15:46:15> ApplyReleasesImpl: About to save shortcut: C:\Users\Umar\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Lucent Web Creative\Game Jolt Client.lnk (target C:\Users\Umar\AppData\Local\GameJoltClient\update.exe, workingDir C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2, args --processStart GameJoltClient.exe)
2016-01-03 15:46:15> ApplyReleasesImpl: Creating shortcut for GameJoltClient.exe => C:\Users\Umar\Desktop\Game Jolt Client.lnk
2016-01-03 15:46:15> ApplyReleasesImpl: About to save shortcut: C:\Users\Umar\Desktop\Game Jolt Client.lnk (target C:\Users\Umar\AppData\Local\GameJoltClient\update.exe, workingDir C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2, args --processStart GameJoltClient.exe)
2016-01-03 15:46:15> ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
2016-01-03 15:46:15> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-01-03 15:46:15> ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
2016-01-03 15:46:15> ApplyReleasesImpl: Fixing up tray icons
2016-01-03 15:46:16> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__f5(RegistryView view)
2016-01-03 15:46:16> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__f5(RegistryView view)
2016-01-03 15:46:16> ApplyReleasesImpl: cleanDeadVersions: for version 0.1.2
2016-01-03 15:46:16> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.1.2
e.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<LogIfThrows>d__4d.MoveNext()
2016-01-03 15:43:48> Unhandled exception: System.AggregateException: Er zijn één of meer fouten opgetreden. ---> System.IO.IOException: Kan geen toegang krijgen tot het bestand C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\lib\net45\GameJoltClient.exe omdat het wordt gebruikt door een ander proces.
   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.File.InternalDelete(String path, Boolean checkHost)
   bij System.IO.File.Delete(String path)
   bij Squirrel.Utility.<DeleteDirectory>b__34(String file)
   bij Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   bij System.Threading.Tasks.Task.InnerInvoke()
   bij System.Threading.Tasks.Task.Execute()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<LogIfThrows>d__4d.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Update.Program.<Install>d__38.MoveNext()
   --- Einde van intern uitzonderingsstackpad ---
   bij System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bij System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bij System.Threading.Tasks.Task.Wait()
   bij Squirrel.Update.Program.executeCommandLine(String[] args)
   bij Squirrel.Update.Program.main(String[] args)
---> (Interne uitzondering #0) System.IO.IOException: Kan geen toegang krijgen tot het bestand C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\lib\net45\GameJoltClient.exe omdat het wordt gebruikt door een ander proces.
   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.File.InternalDelete(String path, Boolean checkHost)
   bij System.IO.File.Delete(String path)
   bij Squirrel.Utility.<DeleteDirectory>b__34(String file)
   bij Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   bij System.Threading.Tasks.Task.InnerInvoke()
   bij System.Threading.Tasks.Task.Execute()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<LogIfThrows>d__4d.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Update.Program.<Install>d__38.MoveNext()<---

2016-01-03 15:48:48> Program: Starting Squirrel Updater: --install .
2016-01-03 15:48:49> Program: Starting install, writing to C:\Users\Umar\AppData\Local\SquirrelTemp
2016-01-03 15:48:49> Program: About to install to: C:\Users\Umar\AppData\Local\GameJoltClient
2016-01-03 15:48:49> Program: Install path C:\Users\Umar\AppData\Local\GameJoltClient already exists, burning it to the ground
2016-01-03 15:48:52> Utility: DeleteDirectory: could not delete - C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\lib\net45\node_modules: System.IO.IOException: De map is niet leeg.

   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   bij System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
2016-01-03 15:48:52> Utility: DeleteDirectory: could not delete - C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\lib\net45: System.IO.IOException: De map is niet leeg.

   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   bij System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
2016-01-03 15:48:52> Utility: DeleteDirectory: could not delete - C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2\lib: System.IO.IOException: De map is niet leeg.

   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   bij System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
2016-01-03 15:48:52> Utility: DeleteDirectory: could not delete - C:\Users\Umar\AppData\Local\GameJoltClient\app-0.1.2: System.IO.IOException: De map is niet leeg.

   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   bij System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
2016-01-03 15:48:52> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.IO.IOException: Kan geen toegang krijgen tot het bestand C:\Users\Umar\AppData\Local\GameJoltClient\packages\GameJoltClient-0.1.2-full.nupkg omdat het wordt gebruikt door een ander proces.
   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.File.InternalDelete(String path, Boolean checkHost)
   bij System.IO.File.Delete(String path)
   bij Squirrel.Utility.<DeleteDirectory>b__34(String file)
   bij Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   bij System.Threading.Tasks.Task.InnerInvoke()
   bij System.Threading.Tasks.Task.Execute()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<LogIfThrows>d__4d.MoveNext()
2016-01-03 15:48:54> Unhandled exception: System.AggregateException: Er zijn één of meer fouten opgetreden. ---> System.IO.IOException: Kan geen toegang krijgen tot het bestand C:\Users\Umar\AppData\Local\GameJoltClient\packages\GameJoltClient-0.1.2-full.nupkg omdat het wordt gebruikt door een ander proces.
   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.File.InternalDelete(String path, Boolean checkHost)
   bij System.IO.File.Delete(String path)
   bij Squirrel.Utility.<DeleteDirectory>b__34(String file)
   bij Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   bij System.Threading.Tasks.Task.InnerInvoke()
   bij System.Threading.Tasks.Task.Execute()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<LogIfThrows>d__4d.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Update.Program.<Install>d__38.MoveNext()
   --- Einde van intern uitzonderingsstackpad ---
   bij System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bij System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bij System.Threading.Tasks.Task.Wait()
   bij Squirrel.Update.Program.executeCommandLine(String[] args)
   bij Squirrel.Update.Program.main(String[] args)
---> (Interne uitzondering #0) System.IO.IOException: Kan geen toegang krijgen tot het bestand C:\Users\Umar\AppData\Local\GameJoltClient\packages\GameJoltClient-0.1.2-full.nupkg omdat het wordt gebruikt door een ander proces.
   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.File.InternalDelete(String path, Boolean checkHost)
   bij System.IO.File.Delete(String path)
   bij Squirrel.Utility.<DeleteDirectory>b__34(String file)
   bij Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   bij System.Threading.Tasks.Task.InnerInvoke()
   bij System.Threading.Tasks.Task.Execute()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Utility.<LogIfThrows>d__4d.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Update.Program.<Install>d__38.MoveNext()<---

**Comment by NikSudan** [comment] 2016-01-04 13:09
Dupe of #436

**Closed by NikSudan** 2016-01-04 13:09 UTC
