### ISSUE TITLE
Gravatar website keep show up when iam started gamejolth client

### ISSUE THREAD

**Issue by Taruna188** [gamejolt/issue-tracker#830] opened 2017-03-05 10:15 UTC
Before gravatar website, iam go to profile and clck gravatar and iam restart the gamejolt client and is keep show up the gravatar website!! what should iam do!?!

**Comment by Taruna188** [comment] 2017-03-05 10:31
plz reply

**Comment by Tricky1975** [comment] 2017-03-05 19:02
It's a known issue, reported countless times before.
All you can do is shut down the client completely (not just closing the window, but a complete shut down. Use the task manager to force it down if nothing helps), and then start the client again, and you should go back to Game Jolt.

**Comment by YLivay** [comment] 2017-03-06 10:47
Quitting normally:
![](http://image.prntscr.com/image/7e3f4a58101843e9a6276ccf6c3aa555.png)

And re-added this to the todo's, somehow slipped away.

**Comment by Tricky1975** [comment] 2017-03-06 16:23
Ah, good to know.... Guess that's what I get for never using Windows 😛

**Comment by mason1920** [comment] 2017-04-02 23:46
Windows is evil, get Debian.

**Comment by Tricky1975** [comment] 2017-04-04 08:41
I agree Windows is crap, but still this is a legit bug that needs to be fixed 😛

**Comment by hworld** [comment] 2017-07-30 22:52
duplicate of https://github.com/gamejolt/issue-tracker/issues/649

**Closed by hworld** 2017-07-30 22:52 UTC
Labels: bug, client, page:user-profile

**Comment by Tricky1975** [comment] 2017-07-31 09:27
> hworld marked this as a duplicate of #649 11 hours ago

Er… I didn’t know this was supported. 
How did you do that or was your message causing the mark to happen automatically?
