### ISSUE TITLE
GameJolt logo is the default avatar insted of the ninja one

### ISSUE THREAD

**Issue by NickRock** [gamejolt/issue-tracker#348] opened 2015-08-02 13:52 UTC
![gj_logo](https://cloud.githubusercontent.com/assets/11754980/9026406/be5f50e0-3936-11e5-882b-b4fc77e8c551.PNG)

**Comment by NikSudan** [comment] 2015-08-02 17:07
Dupe of #331

**Closed by NikSudan** 2015-08-02 17:07 UTC
