### ISSUE TITLE
Won't Open Bug

### ISSUE THREAD

**Issue by littlemoocow** [gamejolt/issue-tracker#534] opened 2016-01-22 18:46 UTC
I've found a **really** annoying bug! The gamejolt client wont open up! I tried to open up the gamejolt installer, and it just said "Installation has failed". I then tried re-installing it, still said the same thing.

**Comment by YLivay** [comment] 2016-01-22 18:47
Dupe of #531 #443 #487

**Closed by YLivay** 2016-01-22 18:47 UTC
