### ISSUE TITLE
Screen names not shown in comment sections

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#862] opened 2017-06-18 19:52 UTC
A user reported this to me on the forums

![](http://i.imgur.com/KoBUTbM.png)
![](http://i.imgur.com/76Ffpsu.png)
![](http://i.imgur.com/JOrASAe.png)

This user had this issue on chrome for Windows and chrome for Android.

I’ve been able to replicate this issue on the next browsers for mac
- Opera
- Chrome
- Firefox
- TorBrowser
- My own mini-MacWebKit browser

I didn’t try Safari, IE or Edge (those are not valid browsers, but junk imho), but I think it’s safe to assume the same trouble will be met there too.

**Comment by niksudan** [comment] 2017-06-18 23:19
Dupe of #860

**Comment by hworld** [comment] 2017-06-18 23:41
looks fine to me

**Comment by hworld** [comment] 2017-06-18 23:46
jk, it's fixed because @niksudan fixed it

**Closed by hworld** 2017-06-18 23:46 UTC
