### ISSUE TITLE
Client mistakenly thinks some games are running after closing/crash

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#428] opened 2015-12-25 02:42 UTC
[Forum Thread](http://gamejolt.com/community/forums/topics/gamejolt-client-problem/14345)
The last person to report the issue mentioned using the windows version.

It might be a good idea to have some safeguard like a manual button or something to bring it out of standby.

**Comment by YLivay** [comment] 2015-12-25 05:49
Duplicate of #399

**Closed by YLivay** 2015-12-25 05:49 UTC
