### ISSUE TITLE
"[Game] received a rating of ."

### ISSUE THREAD

**Issue by Savordez** [gamejolt/issue-tracker#716] opened 2016-06-22 18:21 UTC
![.](http://i.imgur.com/WzyBJ32.png)

Tends to happen sometimes. Dunno. It's kind of random. I was using English (UK) translation.

**Comment by Tricky1975** [comment] 2016-06-26 08:32
This mostly indicates that you were hit by a troll rater who was caught by a site moderator who removed all the ratings. This does however not remove the notification and then you end up with this.

**Comment by hworld** [comment] 2016-06-27 10:48
Closing since it's a duplicate of: https://github.com/gamejolt/issue-tracker/issues/319

This is being worked on, btw. We have a branch of new handling of notifications. It's actually a really big change, so it's slowly being integrated. Hopefully it should clear stuff like this up in the future.

**Closed by hworld** 2016-06-27 10:48 UTC
