### ISSUE TITLE
If I open up gravitar in the Client

### ISSUE THREAD

**Issue by Sandwall** [gamejolt/issue-tracker#649] opened 2016-04-11 00:38 UTC
If I open up gravitar In the client, then I can't go back to gamejolt in the client. I had to restart my computer just to get back to gamejolt. Even if I tried to exit it, then it would open up to gravitar. I had no choice but to restart the computer. So please add a button to the browser of the client that takes you to the gamejolt page.

**Comment by Tricky1975** [comment] 2016-04-11 19:39
I think clicking the link to gravatar was supposed to open your browser and handle your gravatar stuff there.

**Comment by Alobex** [comment] 2016-04-25 23:10
And I have another problem, I opened it one time, and it showed a blank page with nw.js on it. I deleted it, and reinstalled it. Can somebody fix this so that we don't have to reinstall it?

**Comment by Tricky1975** [comment] 2016-04-26 07:42
As far as I know that only happens when the client update failed, and in that case re-installing will have to do. This is btw, unrelated to this issue ;)

**Comment by YLivay** [comment] 2016-05-04 08:52
This is one ugly issue to tackle, we don't have enough info to replicate what exactly might cause client update to go bad. We suspect an overactive antivirus or some other disk restrictions/permissions but even in these cases it shouldn't leave the installation in a corrupt state.

**Comment by Tricky1975** [comment] 2016-08-29 21:55
Since #671 was a dupe of this one, doesn't that mean this one is also fixed?

**Comment by Tricky1975** [comment] 2017-09-26 09:00
Now that we can upload avatars, I wonder?
- Can you upload avatars in the (upcoming version of) the client?
- Of course, if a link to Gravatar remains, this bug can still cause trouble and would still require fixing.

**Comment by Tricky1975** [comment] 2017-09-26 09:02
![image](https://user-images.githubusercontent.com/11202073/30851820-08d330c2-a2aa-11e7-90b2-a1b0aec099df.png)

Note: I don't know why GitHub claims I unassigned @niksudan as all I did was post a reply. As far as I know I don't even have the power to assign or unassign people here.

**Comment by niksudan** [comment] 2017-09-26 09:06
I'm in awe of your power!

**Comment by Tricky1975** [comment] 2017-09-26 10:14
Fear me...

**Comment by YLivay** [comment] 2017-09-26 15:38
Yes, after the rewrite is done, all the features of the site would be available from the client again. Also, the drag in client thing is still tricky, we'll tackle it after the rewrite ofc.

**Comment by hworld** [comment] 2017-12-08 03:54
Fixed in v0.13.0 of client!

**Closed by hworld** 2017-12-08 03:54 UTC
Labels: bug, client
