### ISSUE TITLE
Profile pics not showing up?

### ISSUE THREAD

**Issue by Sharkgamedev** [gamejolt/issue-tracker#1166] opened 2018-08-13 13:47 UTC
![screen shot 2018-08-13 at 9 47 44 am](https://user-images.githubusercontent.com/29334908/44035650-f64a50c6-9edd-11e8-903c-5bff039bdca8.png)
Everybody's profile pic on gamejolt has gone to the gravatar fallback. I tried to re-upload mine with little success, I don't know if this is just me, I'm using the browser version on google chrome MAC-OSX

**Comment by niksudan** [comment] 2018-08-20 09:26
Duplicate of #1165

**Closed by niksudan** 2018-08-20 09:26 UTC
