### ISSUE TITLE
Unable to add images to game description

### ISSUE THREAD

**Issue by niksudan** [gamejolt/issue-tracker#956] opened 2017-08-11 20:05 UTC
Whenever I try to upload an image to the game's description I'm met with a similar invalidation error like with #955. I'm unable to do anything with this image. 

![image](https://user-images.githubusercontent.com/6004491/29229938-b6a41a68-7ed8-11e7-8923-edffdf24b62e.png)

If I remove the image, the error does not go away.

![image](https://user-images.githubusercontent.com/6004491/29229953-c8c3a2c2-7ed8-11e7-988c-aa790777b286.png)

I can save the description, which will save the text but the image will be lost.

**Comment by hworld** [comment] 2017-08-11 20:06
dupe of https://github.com/gamejolt/issue-tracker/issues/952

**Closed by hworld** 2017-08-11 20:06 UTC
