### ISSUE TITLE
Featured Game graphic on homepage can get stuck on the last game

### ISSUE THREAD

**Issue by NALGames** [gamejolt/issue-tracker#133] opened 2015-02-27 08:41 UTC
![newgjfeatured](https://cloud.githubusercontent.com/assets/5822459/6409444/dd1d396c-be5b-11e4-912b-bd260eb5f920.png)

I've noticed that the Featured Game section on the homepage can occasionally lock its graphic to the last game in the carousel (currently "The Darkside Detective"), while the game details continue to change between the ten featured games.

While I don't have a 100% repro for this, I think it's something that has to happen automatically, and after a while - clicking on the last dot to display The Darkside Detective then either clicking on another dot or letting the carousel switch to the first game does not make this happen. I most commonly see this glitch when I've left the homepage open for a while.

Screenshot shows 0h n0 rather than The Darkside Detective as that was the last featured game when I took the screenshot.

**Comment by NALGames** [comment] 2015-02-27 08:43
One other thing to note: once this has happened, the graphic is locked until you change page or refresh. The details will still automatically change, and you can change them by clicking the dots, but the graphic will remain locked.

**Comment by Tricky1975** [comment] 2015-02-27 19:27
I've seen this one as well in Opera for Mac. Assuming NAL uses another browser I guess this is not browser specific.

**Comment by NALGames** [comment] 2015-02-27 19:47
I'm on Chrome, so yeah, it's not browser specific.

**Comment by hworld** [comment] 2015-02-28 19:19
Just want to make sure that you're not leaving the mouse cursor on top of the featured area and then leaving the computer and coming back and not seeing it switch?

**Comment by NALGames** [comment] 2015-02-28 21:07
No, this is from having the site open in one browser tab but using another (or a different program) for a bit, then returning to the GameJolt tab.

**Comment by hworld** [comment] 2015-11-18 19:57
I've never seen this and can't reproduce it. If anyone can come up with repro steps, I can try fixing, but it's been a long time with no complaints. Gonna close it out.

**Closed by hworld** 2015-11-18 19:57 UTC
Labels: bug, page:discover

**Comment by Tricky1975** [comment] 2015-11-19 08:52
I haven't seen this one for awhile either, though it was a present bug at the time this issue was posted. Did somebody else fix this already, or did the issue get fixed due to other steps being taken?

**Comment by hworld** [comment] 2015-11-19 09:34
I really have no clue what changed. It could even be that the major browsers fixed something that was causing it. I had a feeling it was related to CSS animations getting stuck over time...

**Comment by NALGames** [comment] 2015-11-19 09:37
I can confirm I've not seen it happen since that iteration of GameJolt was made public - and I still idle on the home screen a lot.
