### ISSUE TITLE
Forum notifications in client busted (on Mac)

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#653] opened 2016-04-15 20:25 UTC
When I tried to open a notification because somebody replied to a forum post of mine through the client i got this:

![image](https://cloud.githubusercontent.com/assets/11202073/14573972/fafaf698-0358-11e6-8759-a60486d7d3db.png)

**Comment by YLivay** [comment] 2016-05-04 08:50
Does this still happen on 0.4.2?

**Comment by Tricky1975** [comment] 2016-05-04 08:53
Yup

**Comment by YLivay** [comment] 2016-05-04 09:02
Dupe of #642 
Same bug.

**Closed by YLivay** 2016-05-04 09:02 UTC
Labels: bug, component:notifications
