### ISSUE TITLE
i cant get out of gravatar

### ISSUE THREAD

**Issue by salomonhayat** [gamejolt/issue-tracker#840] opened 2017-04-17 23:47 UTC
i just went to change my profile and it wont allow me to go back to the main menu

**Comment by Tricky1975** [comment] 2017-04-21 11:11
Dupes of #830 and #649 
Although I must admit that this is indeed something that takes too long now… :-/

**Comment by hworld** [comment] 2017-07-30 22:52
dupe of https://github.com/gamejolt/issue-tracker/issues/649

**Closed by hworld** 2017-07-30 22:52 UTC
