### ISSUE TITLE
Clicking the avatar of the person who starts a thread leads back to front page in stead of user profile

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#763] opened 2016-09-10 05:39 UTC
When you click inside a forum thread the avatar of the person who began the thread, you'll get back on the Game Jolt front page you see when you enter the site for the first time. Clicking avatars on the replies will get you to the character profiles. Clicking the name of the OP will also get you to the profile.

**Comment by YLivay** [comment] 2016-09-13 21:45
confirmed

**Comment by hworld** [comment] 2017-07-30 23:10
seems to be fixed with the rewrite

**Closed by hworld** 2017-07-30 23:10 UTC
Labels: bug, refactor-fixed, site:forums
