### ISSUE TITLE
Client keep thinking I'm playing

### ISSUE THREAD

**Issue by 3rr3s3v3n** [gamejolt/issue-tracker#529] opened 2016-01-20 13:30 UTC
Hi everybody,
as the title says, gamejolt client thinks I'm playing a game even if it has been shutdown.
No matter try to restart the client or delete the game's folder, the issue persists.

**Comment by YLivay** [comment] 2016-01-20 13:57
Dupe of #488

**Closed by YLivay** 2016-01-20 13:57 UTC
