### ISSUE TITLE
I installed a game, but now it doesn´t close, and I can´t install more games

### ISSUE THREAD

**Issue by Ozoneme** [gamejolt/issue-tracker#400] opened 2015-12-21 00:49 UTC
What can I do??

**Comment by NikSudan** [comment] 2015-12-21 00:53
What OS are you on?

**Comment by YLivay** [comment] 2015-12-21 06:04
Can you also link the game you were playing?

**Comment by wilou** [comment] 2015-12-25 01:06
I have the same problem, the game i was playing is "Empty Soul"

**Comment by YLivay** [comment] 2015-12-25 05:47
Duplicate of #399

**Closed by YLivay** 2015-12-25 05:47 UTC
Labels: bug, client
