### ISSUE TITLE
Client bug

### ISSUE THREAD

**Issue by ChamrongSeng** [gamejolt/issue-tracker#911] opened 2017-07-26 14:07 UTC
When selecting to change my profile avatar on Game Jolt client, it redirected me to Gravatar.com, but still on the client window. After completing all the sign-up on WordPress and Gravatar, the client is now stuck on Gravar homepage without any button to go back to Game Jolt page.

**Comment by hworld** [comment] 2017-07-30 22:52
dupe of https://github.com/gamejolt/issue-tracker/issues/649

**Closed by hworld** 2017-07-30 22:52 UTC
Labels: client
