### ISSUE TITLE
Game installer can't be launched

### ISSUE THREAD

**Issue by 3rr3s3v3n** [gamejolt/issue-tracker#530] opened 2016-01-20 13:36 UTC
Hi everybody,
some games are provided with their custom installer... but the client can't launch it. The only way to install that game is downloading it from the site and launch it manually.

**Comment by YLivay** [comment] 2016-01-20 13:55
GJ Client does not support installers yet.
Dupe of #507, #516

**Closed by YLivay** 2016-01-20 13:55 UTC

**Comment by 3rr3s3v3n** [comment] 2016-01-20 15:19
Ops sorry! :-(
