### ISSUE TITLE
[GJ Client] Clicking a forum notification opens explorer.exe

### ISSUE THREAD

**Issue by maxlefou** [gamejolt/issue-tracker#642] opened 2016-03-28 16:45 UTC
Yep, that's pretty odd. I got a notification about a forum post i did, and when I clicked on it, instead of seeing the forum post, it actually opened a window of explorer.exe. 

I admit, this one made me laugh a bit XD

Tested on the latest update of the client on a Windows 7 x64

**Comment by zombieknifer223** [comment] 2016-03-29 00:29
I know! I got that too! This isn't a big error, but it still needs to be fixed.

**Comment by Tricky1975** [comment] 2016-04-01 17:55
I ticketed this one before (or a similar one), but in my case Opera opened (as that is my default browser. I don't have IE as a Mac user), but it was back then closed, as this because the forums were back then in the new layout, but not properly hooked up to the client. Does the normal forum link in the client show the forum in client or will it also open the browser (not necessarily IE)? Is it really only the notifications?

I shall try to replicate this one on mac.

**Comment by AvianStowaway** [comment] 2016-04-03 17:28
Same here. Silly Gamejolt, I can't get on the forums with a file explorer. :p

**Comment by jellyscallywag** [comment] 2016-04-08 13:00
This thing not only happened to me with forums, same with friend requests.
Besides this I find this issue rather funny.

**Comment by Tricky1975** [comment] 2016-04-08 13:04
It may be funny, but as @hword (CROS) explained in the original ticket (#571), the forum were only recently set up for the new system, and thus the client is not yet properly configured for this.

**Comment by AvianStowaway** [comment] 2016-04-08 18:57
@Tricky1975 Er, that's a different issue. explorer.exe is the Windows File Explorer, not the browser.

**Comment by Tricky1975** [comment] 2016-04-08 19:44
Nope... it's caused by the same thing, and I could even confirm that due to testing. This issue is a dupe of #571 no matter how you put it. It is all due to an outdated configuration. At least as far as the forums are concerned (I could check this on two OSes too).
I don't have any open friend requests at the moment, or I could test this out too.

**Comment by AvianStowaway** [comment] 2016-04-09 15:21
Sorry, I just wasn't sure if you knew what explorer.exe was. You were talking about IE before, which wasn't what was coming up; the file explorer was what was popping up. IE and the file explorer have similar file names (iexplore.exe and explorer.exe), so maybe that has something to do with it.
The two issues are related, you're right there, but something funky is happening with the Windows version of the bug.

**Comment by Tricky1975** [comment] 2016-04-09 15:46
True... On OS X (aka "Mac") everything bugged due to this opens Opera (which is my default browser).
Now I want to try this (it is too much hassle for me to switch to Windows I must disconnect my Mac for that and connect my Windows machine because I've only one monitor, keyboard and mouse).. If there is a link to any external site anywhere on this site, try to open it from within the client. Does that open a browser screen or the file explorer? In case of the latter we got two bugs in one issue here.

**Comment by AvianStowaway** [comment] 2016-04-10 01:43
External links open on the browser, so that works.
So it's definitely the same cause. I just wonder why OS X gets a browser and Windows gets a file explorer. Seems a little, I don't know, inconsistent? Probably gonna be a total mess for people to fix.

**Comment by Tricky1975** [comment] 2016-04-10 11:13
Now I wonder how Linux does this (which I cannot check since I only have 32 bit versions of Linux at my disposal and the client only supports the 64bit versions on of Linux).

**Comment by hworld** [comment] 2017-12-08 03:58
this may have been fixed for a while, but it's definitely fixed now at least with v0.13.0

**Closed by hworld** 2017-12-08 03:58 UTC
Labels: bug, client, component:notifications
