### ISSUE TITLE
{{$count|number}} when hovering mouse over like button.

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/issue-tracker#1087] opened 2018-01-14 18:18 UTC
When hovering your mouse over a greyed out like button, the tool tip which should display how many liked there are, instead displays the variable call: "{{$count|number}}"
Screenshot:
![](https://cdn.discordapp.com/attachments/203287055516565504/402162383419736064/unknown.png)

**Comment by YLivay** [comment] 2018-03-13 20:18
duplicate of #1080

**Closed by YLivay** 2018-03-13 20:18 UTC
