### ISSUE TITLE
Chat messages stay faded out after being sent

### ISSUE THREAD

**Issue by NickRock** [gamejolt/issue-tracker#471] opened 2016-01-09 19:31 UTC
![capture](https://cloud.githubusercontent.com/assets/11754980/12217937/56df60da-b718-11e5-9b18-55867491c8d4.PNG)

**Comment by hworld** [comment] 2016-01-11 03:25
Is this Internet Explorer?

**Comment by NickRock** [comment] 2016-01-16 13:44
No that was on Firefox

**Comment by YLivay** [comment] 2016-02-05 14:46
We love this bug so much we ported it over from the old chat.
This still exists.

**Comment by YLivay** [comment] 2016-08-18 16:22
Yo @Agrosis any update on this?

**Comment by Agrosis** [comment] 2016-08-18 16:53
I've never been able to reproduce this.

**Comment by YLivay** [comment] 2016-08-18 17:24
I've actually not seen this since my last comment either, closing for now, if it happens again we'll reopen.

**Closed by YLivay** 2016-08-18 17:24 UTC
Labels: bug, component:chat
