### ISSUE TITLE
Executable version mismatches in client

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#418] opened 2015-12-22 13:59 UTC
I was only able to test this on Mac though, but here goes.
I tested this out on my "Star Story" Game which has a very detailed version checker, so that's how I could check this.

I tried before to run Star Story in the client, which failed due to a bug on my own side, which I fixed, and I re-uploaded the game, but then I saw something odd.

Star-Story has two applications, the launcher and the engine, and they were in my new update still both on the old version number, however the packed file containing all scripts and assets version number did update, meaning that the client did detect, but somehow it only updated the assets and not the applications themselves. I quit the game, re-started it and checked again, with the same results. Deleting everything completely, then installing the game all over through the client did get everything, the applications AND the assets to the new version.

Now I must note that, I changed the setting of my client in the meantime in order to get all my games on a secondary harddrive as my main is nearly full. Changing this config between the updates might have something to do with it (but nevertheless it should still not happen).

**Comment by YLivay** [comment] 2015-12-22 16:06
Most likely a duplicate of https://github.com/gamejolt/issue-tracker/issues/406.

**Comment by Tricky1975** [comment] 2015-12-22 17:23
Er... no... certainly not a dupe of #406... Perhaps you need to read both issues more thoroughly.

**Comment by YLivay** [comment] 2016-01-08 14:25
Sorry, didnt mean duplicate, meant that its most likely caused by the same bug.
Can you provide the old and new archive files you were testing with so I can make sure it works for you?

I'd like to get this fixed in the next version :)

**Comment by Tricky1975** [comment] 2016-01-08 18:18
Oops, I'm afraid I already deleted the old version even before uploading the new. 
It might however still be floating as an old version on the GJ server. I don't know if I can still download that one somehow.
I can (however) try to upload the current game engine, as a small update to the engine did happen in the time being, meaning the version number of the engine should update in the produced data.

**Comment by YLivay** [comment] 2016-01-10 19:58
Can you link the game then?

**Comment by Tricky1975** [comment] 2016-01-10 20:30
[Sure](http://gamejolt.com/games/star-story/58632)

**Comment by YLivay** [comment] 2016-01-10 21:43
Did you put version numbers on the game? Can you tell me which  version numbers you used that failed upgrading? Did you reuse the version numbers since?

**Comment by Tricky1975** [comment] 2016-01-10 22:03
The game has a launcher, and engine and an asset file, and they all got their own version numbers, they can in-game be called when you run the launcher and click the version tab (you don't have to run the game itself for that). I will have to sort out which version number it was, as I did a few minor updates in the meantime, though I use the "Ubuntu" system for version numbers, so basically based on the date of release, so version 15.12.03 would have been released on Dec 3rd 2015, or yy.mm.dd
So I'll need to calculate back when it was I posted this issue to see which two versions that was as "19 days ago" is hard for me to count back.

(I'm used to ask pesky questions myself in bugfixing my own stuff, and yeah, I'm used to be yelled at as a result too) :sunglasses:

**Comment by YLivay** [comment] 2016-01-10 22:13
Thanks! Are those the version numbers you chose for the releases on GJ as well? or just your internal versioning?

**Comment by Tricky1975** [comment] 2016-01-10 22:14
The version numbers I just gave in my previous post are the version numbers used in the GJ release page. The version numbers inside the game itself my differ, as they are dependent on the last compilation date.

**Comment by YLivay** [comment] 2016-01-10 22:15
Awesome! Looking into this now

**Comment by YLivay** [comment] 2016-01-13 18:55
Should be fixed in new version, But i'm leaving this open till I make sure it works for your game 100%!

**Comment by Tricky1975** [comment] 2016-01-13 22:34
Right, I need some time to prepare a quick "new" version of the game to test this out, so gimme a few more days so I can make sure I can do this safely.

**Comment by YLivay** [comment] 2016-02-05 15:32
Keep us updated man!

**Comment by Tricky1975** [comment] 2016-02-05 22:05
AH yeah, sorry. I shall have to make an update to see what will happen.

Done, well I immediately saw a dialog box older versions didn't show and all version numbers were in order on the last update (and I hadn't used the client (on Mac) since my last update), so that could mean any possible trouble is fixed. (If not, I'll let you know).

**Comment by YLivay** [comment] 2016-02-06 00:04
Awesome! Im closing this then, comment back in this issue if you find anything related and i'll open it back :)

**Closed by YLivay** 2016-02-06 00:04 UTC
Labels: awaiting-feedback, bug, client
