### ISSUE TITLE
Update: [v0.3.2] Follow up on Extracting queuing up forever and ever.

### ISSUE THREAD

**Issue by jianmingyong** [gamejolt/issue-tracker#568] opened 2016-02-09 10:26 UTC
#545 

In previous version, this issue exist when downloading any random game I can find. Now I have narrow down the issue with one of the options.

When I turn off ( Limit simultaneous extractions? - An extraction is when the game is unpacked and installed after downloading. ) the extraction takes forever and ever. If I turn on, it works.

Of course it also means this issue is still in v0.3.0.

**Comment by YLivay** [comment] 2016-02-12 13:08
Yo, can you try reproducing the issue? Then as soon as it happens - scroll down to the footer and hit Send System Report and we'll be able to see exactly what went wrong this time :)

**Comment by jianmingyong** [comment] 2016-02-12 13:41
done :P

**Comment by YLivay** [comment] 2016-02-12 20:25
Hey, sounds like it has issues with the extraction phase when its not limited (lol).
Also, do you have an anti virus? We've got a permission error when trying to remove the old temp download file, which usually means it was being used by something or that our operation was interrupted. There shouldnt be any permission errors because its downloading to your user directory hmm...

Anyways thanks for the system report! It helped find the darn bug :)

**Comment by jianmingyong** [comment] 2016-02-13 09:07
I will try turn off anti virus and try it out. :3

**Comment by jianmingyong** [comment] 2016-02-13 09:56
Edit: Yea, it turns out that my anti virus hate gamejolt client :P 

It doesn't seem to be able to make an exception to stop blocking those file or folder I don't want to scan so I am stuck with limiting extraction for the time being.

**Comment by YLivay** [comment] 2016-02-16 16:50
Haha @jianmingyong thanks for checking!
Always funny when AVs get confused like that. Which one is it, by the way? It might help us catch these issues faster for other users.

As for extractions, i'll try reproducing, but I'm sure #561 will help in this case :)

**Comment by jianmingyong** [comment] 2016-02-16 18:19
AVG 2015 Internet Security.

Extraction when limiting to 1 seem to bypass anti virus checks. It reacts quickly and extract quite fast.

On the other hand, not limiting it seem to take 15 seconds delay or such before it starts to extract.
#BlameAntiVirus for slowing it down.

**Comment by YLivay** [comment] 2016-02-16 20:09
Haha the unlimited vs limited extractions doesnt seem to be the AV's doing. It had to do with being able to restart an operation because it prevented us from removing our downloaded files.

**Comment by jianmingyong** [comment] 2016-02-23 10:51
[v0.3.2] It seem worst than ever, I am sure this time not possible that anti virus block it as I turn it off. It never starts.

Other than limiting to 1 which is still my options, none other work.

**Comment by YLivay** [comment] 2016-02-23 11:40
Nothing changed with v0.3.2 in this regard.

**Comment by YLivay** [comment] 2016-03-28 20:01
This is solved in the new version :)
I'm leaving this open until we push it!

**Comment by YLivay** [comment] 2016-05-04 09:29
Whoops, forgot to close this issue. Been solved ages ago.

**Closed by YLivay** 2016-05-04 09:29 UTC
Labels: bug, client, client:win, component:client-voodoo
