### ISSUE TITLE
API implementation license encouragement

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#593] opened 2016-02-21 10:29 UTC
I noticed that nearly none of the GJ api implementations written by people is properly licensed. This is a legal problem for other projects with using that code.

Of course GJ has no way to enforce a license, but it would be nice if the api documentation mentioned that if anyone creates code implementing the api then it should have a proper license attached. Encourage the authors to add licensing with e.g. LGPL or BSD licenses, which are very permissive and ok to be used in both closed source and in GPL licensed projects.

**Comment by YLivay** [comment] 2016-02-23 17:57
This is a really good idea, but how  would  we go about enforcing licenses?
I think its up to the users to probe the authors to if they intend to use it.

**Comment by CyberKiller40** [comment] 2016-02-23 19:49
Like I said - you can't enforce it (well, unless you make the whole API non-free, like Steam has), but you can encourage it. For existing implementations this is a lost cause, but there will be new ones with the new version of the API, so this might be a good moment.

My suggestion is to write a few paragraphs of text and put it inside the API documentation in a visible spot, so when a coder who wants to write an implementation reads the documentation, he will see the notice about adding a proper code license for his code.

**Comment by YLivay** [comment] 2016-02-23 20:33
We'll make sure to drop a sentence or two in APIv2 when we release it :)

**Comment by hworld** [comment] 2018-10-23 20:28
Gonna close it since it's not a bug, but as we improve the Game API documentation, we'll be sure to encourage this.

**Closed by hworld** 2018-10-23 20:28 UTC
Labels: game-api
